### ISSUE TITLE
Add Cloudflare Worker as a local function deployed on updates

### ISSUE THREAD

**Issue by zpuckeridge** [zpuckeridge/livestream#14]
Cloudflare workers used are completely separate from this repository, meaning project can not be picked up and run with.

If workers are stored in the code locally and updated on Git updates, this should resolve this problem.

**Comment by rhuddlestone** [comment]
HI, nice project, I would like to play around with it after you post the CF Workers code.  Look forward to you posting it.

**Comment by zpuckeridge** [comment]
Hi @rhuddlestone! Thanks for the interest! This is definitely a for-fun project and to get my skills up, but I've gone ahead and added a Wiki page with the Cloudflare Worker code for the interim.

https://github.com/zpuckeridge/livestream/wiki/Getting-Started

Hope that helps!

**Comment by 3C-Wireless** [comment]
Awesome.  I will have a play around with it later today.  Thanks for the super quick response!!

**Comment by rhuddlestone** [comment]
Awesome, I will have a play around with it later today.  Thanks for the super fast response.

**Comment by zpuckeridge** [comment]
Sooo all that code I did in CF Workers was because I couldn't figure out how to use getServerSideProps with my local API.

```// API URL with relevant calls
const baseURL = `https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ID}/stream/`;

// gatherResponse awaits and returns a response body as a string. * Use await gatherResponse(..) in an async function to get the response body * @param {Response} response 
async function gatherResponse(response) {
  const { headers } = response;
  const contentType = headers.get("content-type") || "";
  if (contentType.includes("application/json")) {
    return JSON.stringify(await response.json(), null, 2);
  }
  return response.text();
}

async function handleRequest(id) {
    
  const init = {
    method: "GET",
    headers: { "Access-Control-Allow-Origin": '*', "X-Auth-Key": `${CLOUDFLARE_TOKEN}`, "X-Auth-Email": `${CLOUDFLARE_EMAIL}`, "content-type": "application/json" },
  };

  const response = await fetch(`${baseURL}${id}`, init);
  const results = await gatherResponse(response);

  return new Response(results, init);
}

addEventListener("fetch", (event) => {
// can use if statements here for multi-function
const url = new URL(event.request.url) 
const idMatcher = new RegExp('^\/(?<id>[a-zA-Z0-9\-\%]+)')
const parsedId = url.pathname.match(idMatcher)
  return event.respondWith(handleRequest( parsedId ? parsedId.groups.id : "" ));
});
```

Sooooooooooooooooooo, turns out, I'm dumb

I can just do this:

```const res = await fetch(`${process.env.PAGE_URL}/api/stream`);```

Where `PAGE_URL` uses the set ENV variable.

Instead of:

```fetch(`${process.env.CLOUDFLARE_WORKER}`);```

Where `CLOUDFLARE_WORKER` is the CF Worker URL.

Because I'm using in the internal API, the code can now be this simple:

```
import { NextApiRequest, NextApiResponse } from "next";

export default async (req: NextApiRequest, res: NextApiResponse) => {
  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ID}/stream/`,
    {
      method: "GET",
      headers: {
        "X-Auth-Key": `${process.env.CLOUDFLARE_TOKEN}`,
        "X-Auth-Email": `${process.env.CLOUDFLARE_EMAIL}`,
        "Content-Type": "application/json",
      },
    }
  );
  const data = await response.json();
  res.status(200).json(data);
};
```
