### ISSUE TITLE
Unauthorised

### ISSUE THREAD

**Issue by Rstacx** [zpuckeridge/livestream#302]
When I sign up and go to the dashboard, it says unauthorized.
I can't access the dashboard even after I log out and sign in again.
How to fix it?

**Comment by zpuckeridge** [comment]
G'day mate! Have you updated the user id in the middleware?

You've likely got to go to Clerk and grab your ID and paste that into the middleware.

https://github.com/zpuckeridge/livestream/blob/main/middleware.ts

It should be an environment variable, I've just not changed it over yet!
