### ISSUE TITLE
Deploying on Cloudflare Pages

### ISSUE THREAD

**Issue by rhuddlestone** [zpuckeridge/livestream#33]
Hi Zac (I hope I spelled it right). Do you have any guidance for deploying on Cloudflare Pages?  I tried to deploy, and the build succeeded but I got a 404 when I went to the page's URL.  Deployment on Vercel works fine, so maybe I missed something for pages (probably some SSR stuff). 

Keep up the good work.

**Comment by zpuckeridge** [comment]
Hi @rhuddlestone! This used to work, but is currently blocked due to my upgrade to Next 13.

Cloudflare Pages does not have support for Next 13 as yet, but it is just around the corner!

**Comment by rhuddlestone** [comment]
Thanks, Vercel is working fine so no problem.

**Comment by Erisa** [comment]
Is there still something blocking this?

I notice the readme says
>  A Next.JS project leveraging Cloudflare Stream, Cloudflare Workers, Tailwind CSS all hosted on Cloudflare Pages. 

But not sure if that;s true or how to host on Pages if it is

**Comment by zpuckeridge** [comment]
Hi @Erisa! Early iterations of this project were using Cloudflare Pages, but as the scope expanded, I had to move away from it due to the issues I encountered with using Next 13. I've updated the readme now in 4273e9a.
